- name: ensure upstart script for slack bot app is in place
  template:
    src: slack_bot.conf
    dest: /etc/init

- name: check if deployment dir exists
  stat:
    path: "{{site_path}}"
  register: site_path_check

- name: start app
  service:
    name: slack_bot
    state: restarted
  when: "{{site_path_check.stat.exists}}"
