# All project build tasks go here. These tasks will only be run for the
# specified commit if the commit hasn't been deployed before or if "force"
# is true.

# Modify as-needed!

- name: compare package.json of current deploy with previous deploy
  command: diff {{site_path}}/package.json {{clone_path}}/package.json
  register: package_diff
  ignore_errors: true
  no_log: true

- name: install npm modules
  npm: path="{{clone_path}}"
