# All project build tasks go here. These tasks will only be run for the
# specified commit if the commit hasn't been deployed before or if "force"
# is true.

# Modify as-needed!

- name: compare package.json of current deploy with previous deploy
  command: diff {{site_path}}/package.json {{clone_path}}/package.json
  register: package_diff
  changed_when: false
  ignore_errors: true
  no_log: true

- name: install npm modules
  npm: path="{{clone_path}}"
  when: package_diff.rc != 0

- name: copy existing npm modules
  command: cp -R {{site_path}}/node_modules {{clone_path}}
  when: package_diff.rc == 0

- name: ensure database has the latest migrations
  shell: "npm run migrate:up"
  args:
    chdir: "{{clone_path}}"
